version: '3.0'
services:
  frontend:
    container_name: frontend
    build:
      context: ../aichat-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - postgres
      - minio
  postgres:
    container_name: pgvector
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=chat
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=rbH19wfjs7wD0Uu
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  minio:
    image: bitnami/minio:2022.7.26
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: rbH19wfjs7wD0Uu
      MINIO_DEFAULT_BUCKETS: public